### ISSUE TITLE
PHP 7.2 - Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by ondrakub** [ublaboo/mailing#8]
- bug report? yes
- feature request? no
- version: 1.1.5

Description

- PHP 7.2 uses "Object" as typehint (https://wiki.php.net/rfc/object-typehint).
- Tested with "php:7.2.0RC5".

**Comment by paveljanda** [comment]
@ondrakub Can you send a PR?

**Comment by ondrakub** [comment]
@paveljanda yes, I'll prepare it

**Comment by ondrakub** [comment]
@paveljanda  done in #9

**Comment by ondrakub** [comment]
@paveljanda Hi, can you please merge this PR? PHP 7.2 is out and I am waiting for month to update this library.

**Comment by paveljanda** [comment]
@ondrakub Done. Thanks.
